# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170201_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
